version: '3.0'
services:
    guard:
        container_name: guard
        image: guard
        hostname: guard
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        networks:
            - app-network
        command: start
networks:
  app-network:
    driver: bridge